[tls]
  [tls.options]
    [tls.options.mtls-required]
      [tls.options.mtls-required.clientAuth]
        # in PEM format. each file can contain multiple CAs.
        # caFiles can be an authority, or a list of clients
#        caFiles = ["/pki/ca/signing-ca.crt"]
        caFiles = [
          "/pki/certs/alice.crt",
#          "/pki/certs/bob.crt",
          "/pki/certs/charlie.crt"
        ]
        clientAuthType = "RequireAndVerifyClientCert"

    [tls.options.modern]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
      curvePreferences = ["CurveP521", "CurveP384"]
      sniStrict = true

  [[tls.certificates]]
    certFile = "/pki/certs/srv-localhost.crt"
    keyFile = "/pki/certs/srv-localhost.key"

